# frozen_string_literal: true

source 'https://rubygems.org'
gem 'activemodel'

group :test do
  gem 'rspec'
  gem 'rubocop'
  gem 'rubocop-rspec', require: false
  gem 'simplecov', require: false
end

group :development, :test do
  gem 'debug', '>= 1.0.0'
end
